name: Upgrade if there is a new upstream release
on: 
  schedule:
    - cron: "0 0 * * 0"
  push:
jobs:
  check_upstream_version:
    name: Check upstream version
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - run: ./update.sh --update

