name: Upgrade if there is a new upstream release
on: 
  schedule:
    - cron: "0 0 * * 0"
  push:
jobs:
  check_upstream_version:
    env:
      GIT_USER_NAME: "GitHub Action"
      GIT_USER_EMAIL: "action@github.com"
      GITHUB_TOKEN: ${{ secrets.token }}
    name: Check upstream version
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - run: ./update.sh --update

